export const COMMON_MENU_PINED_AREA_MIN_HEIGHT = 144
export const COMMON_MENU_PINED_AREA_SINGLE_MIN_HEIGHT = 48
export const COMMON_MENU_PINED_AREA_HEADER_HEIGHT = 28
export const COMMON_MENU_DIVIDER_DEFAULT_HEIGHT = 24

export const MINI_MENU_PINED_AREA_MIN_HEIGHT = 144
export const MINI_MENU_PINED_AREA_HEADER_HEIGHT = 0
export const MINI_MENU_DIVIDER_HEIGHT = 9

export const RECENT_TAB_AREA_MIN_HEIGHT = 96
